services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TOOLHIVE_AUTH_TOKEN=${TOOLHIVE_AUTH_TOKEN:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
