---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: toolhive-operator-leader-election-role
  namespace: toolhive-system
  labels:
    app.kubernetes.io/name: toolhive-operator
    app.kubernetes.io/part-of: toolhive-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: toolhive-operator-leader-election-rolebinding
  namespace: toolhive-system
  labels:
    app.kubernetes.io/name: toolhive-operator
    app.kubernetes.io/part-of: toolhive-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: toolhive-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: toolhive-operator
  namespace: toolhive-system